/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package udpserver;

import java.io.IOException;
import java.net.SocketException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author INSECT
 */
public class ServerJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ServerJFrame
     */
    public ServerJFrame() {
        initComponents();
   
        UdpServer.addMyEventListener(new UdpServer.ReceivedMessageListener() {

            @Override
            public void MessageReceived(UdpServer.ReceivedMessage evt) {
                
                    }

            @Override
            public void MessageReceived(String evt) {
                txta_receivedmessage.append("\n"+evt);
                
            }
        });
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_start = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_message = new javax.swing.JTextArea();
        btn_send = new javax.swing.JButton();
        btn_create = new javax.swing.JButton();
        txtf_port = new javax.swing.JTextField();
        btn_stop = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txta_receivedmessage = new javax.swing.JTextArea();
        txtf_filepath = new javax.swing.JTextField();
        btn_sendfile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_start.setText("Start");
        btn_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_startMouseClicked(evt);
            }
        });
        getContentPane().add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 33, 68, -1));

        txta_message.setColumns(20);
        txta_message.setRows(5);
        jScrollPane1.setViewportView(txta_message);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 107, 246, 161));

        btn_send.setText("Send");
        btn_send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sendMouseClicked(evt);
            }
        });
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });
        getContentPane().add(btn_send, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 279, 246, -1));

        btn_create.setText("Create");
        btn_create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_createMouseClicked(evt);
            }
        });
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });
        getContentPane().add(btn_create, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 33, -1, -1));

        txtf_port.setText("8000");
        getContentPane().add(txtf_port, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 34, 56, -1));

        btn_stop.setText("Stop");
        btn_stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_stopMouseClicked(evt);
            }
        });
        getContentPane().add(btn_stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 62, 68, -1));

        txta_receivedmessage.setColumns(20);
        txta_receivedmessage.setRows(5);
        jScrollPane2.setViewportView(txta_receivedmessage);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 107, 230, 161));

        txtf_filepath.setText("C:\\Users\\samet\\Desktop\\dosya.txt");
        getContentPane().add(txtf_filepath, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 320, 246, -1));

        btn_sendfile.setText("Send File");
        btn_sendfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sendfileMouseClicked(evt);
            }
        });
        btn_sendfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendfileActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sendfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 358, 246, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sendActionPerformed

    private void btn_createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_createMouseClicked
    
        try {
            // TODO add your handling code here:
           
            UdpServer.Create( Integer.valueOf(txtf_port.getText()));
        } catch (SocketException ex) {
            System.out.println(ex.getMessage());
        }
       
    }//GEN-LAST:event_btn_createMouseClicked

    private void btn_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_startMouseClicked
            // TODO add your handling code here:
        UdpServer.Start();
    }//GEN-LAST:event_btn_startMouseClicked

    private void btn_sendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sendMouseClicked
        try {
            // TODO add your handling code here:
            
            UdpServer.SentMessage(txta_message.getText());
        } catch (IOException ex) {
           
        }
    }//GEN-LAST:event_btn_sendMouseClicked

    private void btn_stopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_stopMouseClicked
        // TODO add your handling code here:
        UdpServer.Stop();
    }//GEN-LAST:event_btn_stopMouseClicked

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_createActionPerformed

    private void btn_sendfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sendfileMouseClicked
        try {
            // TODO add your handling code here:
            UdpServer.SendFile(txtf_filepath.getText());
        } catch (IOException ex) {
            Logger.getLogger(ServerJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btn_sendfileMouseClicked

    private void btn_sendfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sendfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_create;
    private javax.swing.JButton btn_send;
    private javax.swing.JButton btn_sendfile;
    private javax.swing.JButton btn_start;
    private javax.swing.JButton btn_stop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txta_message;
    private javax.swing.JTextArea txta_receivedmessage;
    private javax.swing.JTextField txtf_filepath;
    private javax.swing.JTextField txtf_port;
    // End of variables declaration//GEN-END:variables
}
